module.exports.descriptors = [
    'Western',
    'Chinese',
    'Malay',
    'Indian',
    'Italian',
    'Mexican',
    'French',
    'Fusion'
]

const type = [
    'Dessert',
    'Main',
    'Ala-carte'
]

module.exports.title = [
    "Savoria",
    "Flavorful Bites",
    "The Hungry Fork",
    "Culinary Delights",
    "Gourmet Garden",
    "Taste of Joy",
    "The Spice Route",
    "Epicurean Haven",
    "Soulful Eats",
    "Palate Pleasers",
    "Feast & Frolic",
    "Aroma Junction",
    "The Savory Spot",
    "Zestful Zing",
    "The Gastronomy House",
    "Tantalizing Temptations",
    "Sizzle & Spice",
    "The Food Lab",
    "Munchies Galore",
    "Flaming Flavors",
    "Taste Oasis",
    "Gusto Grill",
    "Foodie's Paradise",
    "The Wholesome Plate",
    "Umami Delight",
    "Bistro Bliss",
    "Yummy Junction",
    "Gourmet Alley",
    "The Epicure's Nest",
    "Food Haven",
    "Saucy Delights",
    "Spice Fusion",
    "Hearty Bites",
    "Zesty Zestaurant",
    "The Flavor Factory",
    "The Gourmet Corner",
    "Savory Central",
    "Taste Treats",
    "Mouthwatering Moments",
    "Delicious Diner",
    "Tasty Trails",
    "Savor Street",
    "The Culinary Haven",
    "Belly Bliss",
    "Saucy Secrets",
    "The Flavorful Fork",
    "The Gastronomic Spot",
    "Gusto Grind",
    "Sizzle Street",
    "Foodie's Delight",
    "The Wholesome Haven",
    "Zestful Zestaurant",
    "The Flavor Haven",
    "Spice Street",
    "Hearty Haven",
    "Taste Temptations",
    "Munchies Corner",
    "Flaming Delights",
    "Taste Central",
    "Gourmet Grind",
    "Umami Street",
    "The Epicure's Nest",
    "Foodie's Haven",
    "Saucy Street",
    "The Flavor Fusion",
    "The Gourmet Haven",
    "Savory Secrets",
    "Taste Factory",
    "Mouthwatering Corner",
    "Delicious Delights",
    "Tasty Treats",
    "Savor Secrets",
    "The Culinary Street",
    "Belly Bites",
    "Saucy Street",
    "The Flavorful Haven",
    "Gusto Secrets",
    "Sizzle Haven",
    "Foodie's Treat",
    "The Wholesome Fusion",
    "Zestful Haven",
    "The Flavor Factory",
    "Spice Haven",
    "Hearty Treats",
    "Taste Street",
    "Munchies Haven",
    "Flaming Secrets",
    "Taste Grind",
    "Gourmet Street",
    "Umami Haven"
]
